application: enproxy
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
  
- url: /enproxy.py
  script: enproxy.py
  secure: optional
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: index.py
  
